print("\t \t\tDDAMU TRADERS LTD KIKUUBO\t\t")
print("\t \t\t0751006090/0785098978\t\t\n")
print()
print("\t-------------------------------------------------\t")
print("\t| \t\t\tRECEIPT\t\t\t|")
print("\t| \t\t\t\t\t\t|")
print("\t| Receipt No: 918\t\t\t\t|")
print("\t| Date: 17-Jan-24\t\t\t\t|")
print("\t| Time: 1:20 PM\t\t\t\t\t|")
print("\t| Item: Nido 400g  Qty: 1pc  Amount: 40000\t|")
print("\t| Cash Received 50000\t\t\t\t|")
print("\t| Cash Change 10000\t\t\t\t|")
print("\t| Served by:  Jamil\t\t\t\t|")
print("\t-------------------------------------------------\n")
print()
print("\t Once goods sold are not returnable")
print("\t Thank you for shopping with DDAMU TRADERS LTD")